# Exploratory Data Analysis (EDA) - Dataset de ortopedia

.
Este notebook contem todo o processo de exploração de dados da base de dados fornecida "ML_Ortopedia_CPAK" de forma a entender a estrutura, distribuições, relacões e identificar potenciais padrões para desenvolver um modelo de Machine learning
## 1. Visão geral dos dados e informação básica

In [58]:
# importar dados como dataframe
import pandas as pd

ortho = pd.read_excel('ML_Ortopedia_CPAK.xlsx')

In [59]:
# verificar estrutura do dataframe
ortho.shape

(265, 22)

In [60]:
#verificar as primeiras linhas do dataframe
ortho.head()

,Idade,Sexo,Peso,Altura_cm,IMC,Grupo_pre,Grupo_pos,Fle_0,EVA_0,PM6_0,...,WAtotal_0,WT_0,Fle_90,EVA_90,PM6_90,WD_90,WR_90,WAtotal_90,WT_90,Satisfação
0,67,1,80,158,32.046146,5.0,5,86,4,324,...,54,75,80,1,290,5,1,9,15,8
1,76,2,60,155,24.973985,5.0,5,90,4,357,...,39,60,110,1,480,5,4,3,12,9
2,72,2,93,182,28.076319,1.0,1,45,10,289,...,53,72,100,0,388,0,0,0,0,10
3,67,2,71,163,26.722873,6.0,6,127,2,390,...,16,18,100,0,387,2,0,10,12,9
4,66,1,49,160,19.140625,6.0,6,120,0,285,...,8,8,125,1,284,0,1,2,3,7

In [62]:
# ver os tipos de dados do dataframe
ortho.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Idade       265 non-null    int64
 1   Sexo        265 non-null    int64
 2   Peso        265 non-null    int64
 3   Altura_cm   265 non-null    int64
 4   IMC         265 non-null    float64
 5   Grupo_pre   262 non-null    float64
 6   Grupo_pos   265 non-null    int64
 7   Fle_0       265 non-null    int64
 8   EVA_0       265 non-null    int64
 9   PM6_0       265 non-null    int64
 10  WD_0        265 non-null    int64
 11  WR_0        265 non-null    int64
 12  WAtotal_0   265 non-null    int64
 13  WT_0        265 non-null    int64
 14  Fle_90      265 non-null    int64
 15  EVA_90      265 non-null    int64
 16  PM6_90      265 non-null    int64
 17  WD_90       265 non-null    int64
 18  WR_90       265 non-null    int64
 19  WAtotal_90  265 non-null    int64
 20  WT_90       265 non-null    int64
 21  Satisfação  265 non-null    int64
dtypes: float64(2), int64(20)
memory usage: 45.7 KB

In [67]:
# verificar se existem linhas duplicadas
ortho.duplicated().sum()

np.int64(0)

In [63]:
#verificação de valores nulos
ortho.isnull().sum()

Idade         0
Sexo          0
Peso          0
Altura_cm     0
IMC           0
Grupo_pre     3
Grupo_pos     0
Fle_0         0
EVA_0         0
PM6_0         0
WD_0          0
WR_0          0
WAtotal_0     0
WT_0          0
Fle_90        0
EVA_90        0
PM6_90        0
WD_90         0
WR_90         0
WAtotal_90    0
WT_90         0
Satisfação    0
dtype: int64

In [ ]:
#visualizar os casos que possuem valores nulos, listando por linha 
missing_values = ortho[ortho['Grupo_pre'].isnull()]
missing_values

,Idade,Sexo,Peso,Altura_cm,IMC,Grupo_pre,Grupo_pos,Fle_0,EVA_0,PM6_0,...,WAtotal_0,WT_0,Fle_90,EVA_90,PM6_90,WD_90,WR_90,WAtotal_90,WT_90,Satisfação
259,67,1,76,160,29.687500,NaN,2,150,3,480,...,23,36,123,0,460,0,6,12,18,9
260,73,1,71,153,30.330215,NaN,8,92,8,220,...,41,57,115,1,340,1,1,16,18,10
261,77,2,63,161,24.304618,NaN,4,130,7,160,...,44,59,110,0,280,0,1,6,7,10

In [ ]:
# eliminar os casos com valores nulos, pois são poucos e não devem impactar a análise
ortho1 = ortho.dropna(subset = ['Grupo_pre'])

In [ ]:
# verificar novamente a presença de valores nulos
ortho1.isnull().sum()

Idade         0
Sexo          0
Peso          0
Altura_cm     0
IMC           0
Grupo_pre     0
Grupo_pos     0
Fle_0         0
EVA_0         0
PM6_0         0
WD_0          0
WR_0          0
WAtotal_0     0
WT_0          0
Fle_90        0
EVA_90        0
PM6_90        0
WD_90         0
WR_90         0
WAtotal_90    0
WT_90         0
Satisfação    0
dtype: int64

In [69]:
# substituição da codificação da variavel 'Sexo' por outros valores numéricos para não induzir o modelo em erro  
# original 1: feminino, 2: masculino
# nova codificação 0: feminino, 1: masculino
ortho1.replace({'Sexo': {1: 0, 2: 1}}, inplace = True)

C:\Users\edu23\AppData\Local\Temp\ipykernel_4248\91962884.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1.replace({'Sexo': {1: 0, 2: 1}}, inplace = True)

In [22]:
# converter a variavel "Grupo_pre" para o tipo int
ortho1['Grupo_pre'] = ortho1['Grupo_pre'].astype(int)

C:\Users\edu23\AppData\Local\Temp\ipykernel_4248\2837699438.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1['Grupo_pre'] = ortho1['Grupo_pre'].astype(int)

In [ ]:
# gerar a variavel de interesse "mudanca_CPAK" que indica se houve mudança no grupo de classificação entre o pré e o pós-operatório.
ortho1['mudanca_CPAK'] = (ortho1['Grupo_pre'] != ortho1['Grupo_pos']).astype(int)

In [35]:
mudanca_counts = ortho1['mudanca_CPAK'].value_counts()
print(mudanca_counts)

mudanca_CPAK
0    236
1     26
Name: count, dtype: int64

In [ ]:
# verificar o numero de linhas e de colunas após a limpeza dos dados
ortho1.shape

np.int64(0)

In [ ]:
# verificar os tipos de variaveis 
ortho1.info()

(262, 23)

In [ ]:
# verificar se existem linhas duplicadas
ortho1.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 262 entries, 0 to 264
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Idade         262 non-null    int64
 1   Sexo          262 non-null    int64
 2   Peso          262 non-null    int64
 3   Altura_cm     262 non-null    int64
 4   IMC           262 non-null    float64
 5   Grupo_pre     262 non-null    int64
 6   Grupo_pos     262 non-null    int64
 7   Fle_0         262 non-null    int64
 8   EVA_0         262 non-null    int64
 9   PM6_0         262 non-null    int64
 10  WD_0          262 non-null    int64
 11  WR_0          262 non-null    int64
 12  WAtotal_0     262 non-null    int64
 13  WT_0          262 non-null    int64
 14  Fle_90        262 non-null    int64
 15  EVA_90        262 non-null    int64
 16  PM6_90        262 non-null    int64
 17  WD_90         262 non-null    int64
 18  WR_90         262 non-null    int64
 19  WAtotal_90    262 non-null    int64
 20  WT_90         262 non-null    int64
 21  Satisfação    262 non-null    int64
 22  mudanca_CPAK  262 non-null    int64
dtypes: float64(1), int64(22)
memory usage: 57.2 KB

In [80]:
# avaliar consistencia dos dados, verificando se existem valores fora do esperado para cada variavel
ortho1.describe()

,Idade,Sexo,Peso,Altura_cm,IMC,Grupo_pre,Grupo_pos,Fle_0,EVA_0,PM6_0,...,Fle_90,EVA_90,PM6_90,WD_90,WR_90,WAtotal_90,WT_90,Satisfação,IMC_check,mudanca_CPAK
count,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,...,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000
mean,71.133588,0.362595,84.377863,169.038168,36.565258,4.595420,4.309160,116.858779,28.309160,263.759542,...,112.667939,16.767176,315.606870,2.729008,1.270992,10.740458,14.740458,46.633588,29.015716,0.099237
std,7.658498,0.481669,81.752397,73.659921,84.693225,1.581883,1.683772,97.667192,148.909188,130.702931,...,79.091249,122.551933,108.510827,2.455551,1.286177,7.969855,10.269613,190.084704,4.816238,0.299552
min,47.000000,0.000000,32.000000,136.000000,14.222222,1.000000,1.000000,10.000000,0.000000,0.000000,...,70.000000,0.000000,121.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10.010010,0.000000
25%,66.000000,0.000000,66.250000,155.000000,26.147508,4.000000,3.000000,95.000000,4.000000,180.000000,...,95.000000,0.000000,249.000000,1.000000,0.000000,5.000000,8.000000,8.000000,26.067084,0.000000
50%,72.000000,0.000000,76.000000,162.000000,28.725735,5.000000,5.000000,110.000000,6.000000,253.500000,...,105.000000,1.000000,300.000000,2.000000,1.000000,9.000000,13.000000,10.000000,28.697812,0.000000
75%,76.000000,1.000000,86.750000,170.000000,32.015277,6.000000,5.000000,120.000000,8.000000,330.000000,...,116.000000,3.000000,360.000000,4.000000,2.000000,15.000000,20.000000,10.000000,31.807302,0.000000
max,89.000000,1.000000,999.000000,999.000000,999.000000,9.000000,9.000000,999.000000,999.000000,999.000000,...,999.000000,999.000000,999.000000,11.000000,8.000000,40.000000,55.000000,999.000000,42.324275,1.000000

In [79]:
ortho1['mudanca_CPAK'] = (ortho1['Grupo_pre'] != ortho1['Grupo_pos']).astype(int)

C:\Users\edu23\AppData\Local\Temp\ipykernel_4248\2327009059.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1['mudanca_CPAK'] = (ortho1['Grupo_pre'] != ortho1['Grupo_pos']).astype(int)

In [92]:
# verificar estes outliers de 999 em quase todas as variaveis, exceto "Grupo_pre" e "Grupo_pos"
ortho1[ortho1 == 999].count()

Idade            0
Sexo             0
Peso             2
Altura_cm        2
IMC              2
Grupo_pre        0
Grupo_pos        0
Fle_0            3
EVA_0            6
PM6_0            3
WD_0             0
WR_0             0
WAtotal_0        1
WT_0             0
Fle_90           2
EVA_90           4
PM6_90           2
WD_90            0
WR_90            0
WAtotal_90       0
WT_90            0
Satisfação      10
IMC_check        0
mudanca_CPAK     0
IMC_calc         0
dtype: int64

In [95]:
#converter 999 em NaN para facilitar a análise e evitar que esses valores sejam interpretados como válidos
import numpy as np 
ortho1.replace(999, np.nan, inplace=True)

C:\Users\edu23\AppData\Local\Temp\ipykernel_4248\1093518942.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1.replace(999, np.nan, inplace=True)

In [96]:
# Verificação se ainda existem variaveis com valores de 999
ortho1[ortho1 == 999].count()

Idade           0
Sexo            0
Peso            0
Altura_cm       0
IMC             0
Grupo_pre       0
Grupo_pos       0
Fle_0           0
EVA_0           0
PM6_0           0
WD_0            0
WR_0            0
WAtotal_0       0
WT_0            0
Fle_90          0
EVA_90          0
PM6_90          0
WD_90           0
WR_90           0
WAtotal_90      0
WT_90           0
Satisfação      0
IMC_check       0
mudanca_CPAK    0
IMC_calc        0
dtype: int64

In [ ]:
# separar as variaveis numéricas de variaveis categóricas
var_num = ortho1.