# Exploratory Data Analysis (EDA) - Dataset de ortopedia

.
Este notebook contem todo o processo de exploração de dados da base de dados fornecida "ML_Ortopedia_CPAK" de forma a entender a estrutura, distribuições, relacões e identificar potenciais padrões para desenvolver um modelo de Machine learning
## 1. Visão geral dos dados e informação básica

In [1]:
# importar dados como dataframe
import pandas as pd

ortho = pd.read_excel('ML_Ortopedia_CPAK.xlsx')

In [2]:
# verificar estrutura do dataframe
ortho.shape

(265, 22)

In [3]:
#verificar as primeiras linhas do dataframe
ortho.head()

,Idade,Sexo,Peso,Altura_cm,IMC,Grupo_pre,Grupo_pos,Fle_0,EVA_0,PM6_0,...,WAtotal_0,WT_0,Fle_90,EVA_90,PM6_90,WD_90,WR_90,WAtotal_90,WT_90,Satisfação
0,67,1,80,158,32.046146,5.0,5,86,4,324,...,54,75,80,1,290,5,1,9,15,8
1,76,2,60,155,24.973985,5.0,5,90,4,357,...,39,60,110,1,480,5,4,3,12,9
2,72,2,93,182,28.076319,1.0,1,45,10,289,...,53,72,100,0,388,0,0,0,0,10
3,67,2,71,163,26.722873,6.0,6,127,2,390,...,16,18,100,0,387,2,0,10,12,9
4,66,1,49,160,19.140625,6.0,6,120,0,285,...,8,8,125,1,284,0,1,2,3,7

In [4]:
# ver os tipos de dados do dataframe
ortho.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Idade       265 non-null    int64
 1   Sexo        265 non-null    int64
 2   Peso        265 non-null    int64
 3   Altura_cm   265 non-null    int64
 4   IMC         265 non-null    float64
 5   Grupo_pre   262 non-null    float64
 6   Grupo_pos   265 non-null    int64
 7   Fle_0       265 non-null    int64
 8   EVA_0       265 non-null    int64
 9   PM6_0       265 non-null    int64
 10  WD_0        265 non-null    int64
 11  WR_0        265 non-null    int64
 12  WAtotal_0   265 non-null    int64
 13  WT_0        265 non-null    int64
 14  Fle_90      265 non-null    int64
 15  EVA_90      265 non-null    int64
 16  PM6_90      265 non-null    int64
 17  WD_90       265 non-null    int64
 18  WR_90       265 non-null    int64
 19  WAtotal_90  265 non-null    int64
 20  WT_90       265 non-null    int64
 21  Satisfação  265 non-null    int64
dtypes: float64(2), int64(20)
memory usage: 45.7 KB

In [5]:
# verificar se existem linhas duplicadas
ortho.duplicated().sum()

np.int64(0)

In [6]:
#verificação de valores nulos
ortho.isnull().sum()

Idade         0
Sexo          0
Peso          0
Altura_cm     0
IMC           0
Grupo_pre     3
Grupo_pos     0
Fle_0         0
EVA_0         0
PM6_0         0
WD_0          0
WR_0          0
WAtotal_0     0
WT_0          0
Fle_90        0
EVA_90        0
PM6_90        0
WD_90         0
WR_90         0
WAtotal_90    0
WT_90         0
Satisfação    0
dtype: int64

In [ ]:
#visualizar os casos que possuem valores nulos, listando por linha 
missing_values = ortho[ortho['Grupo_pre'].isnull()]
missing_values

,Idade,Sexo,Peso,Altura_cm,IMC,Grupo_pre,Grupo_pos,Fle_0,EVA_0,PM6_0,...,WAtotal_0,WT_0,Fle_90,EVA_90,PM6_90,WD_90,WR_90,WAtotal_90,WT_90,Satisfação
259,67,1,76,160,29.687500,NaN,2,150,3,480,...,23,36,123,0,460,0,6,12,18,9
260,73,1,71,153,30.330215,NaN,8,92,8,220,...,41,57,115,1,340,1,1,16,18,10
261,77,2,63,161,24.304618,NaN,4,130,7,160,...,44,59,110,0,280,0,1,6,7,10

In [8]:
# eliminar os casos com valores nulos, pois são poucos e não devem impactar a análise
ortho1 = ortho.dropna(subset = ['Grupo_pre'])

In [9]:
# verificar novamente a presença de valores nulos
ortho1.isnull().sum()

Idade         0
Sexo          0
Peso          0
Altura_cm     0
IMC           0
Grupo_pre     0
Grupo_pos     0
Fle_0         0
EVA_0         0
PM6_0         0
WD_0          0
WR_0          0
WAtotal_0     0
WT_0          0
Fle_90        0
EVA_90        0
PM6_90        0
WD_90         0
WR_90         0
WAtotal_90    0
WT_90         0
Satisfação    0
dtype: int64

In [12]:
# substituição da codificação da variavel 'Sexo' por outros valores numéricos para não induzir o modelo em erro  
# original 1: feminino, 2: masculino
# nova codificação 0: feminino, 1: masculino
#
ortho1.replace({'Sexo': {1: 0, 2: 1}}, inplace = True)

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_20352\1957548313.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1.replace({'Sexo': {1: 0, 2: 1}}, inplace = True)

In [13]:
# converter a variavel "Grupo_pre" para o tipo int
ortho1['Grupo_pre'] = ortho1['Grupo_pre'].astype(int)

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_20352\2837699438.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1['Grupo_pre'] = ortho1['Grupo_pre'].astype(int)

In [14]:
# gerar a variavel de interesse "mudanca_CPAK" que indica se houve mudança no grupo de classificação entre o pré e o pós-operatório.
ortho1['mudanca_CPAK'] = (ortho1['Grupo_pre'] != ortho1['Grupo_pos']).astype(int)

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_20352\98550120.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1['mudanca_CPAK'] = (ortho1['Grupo_pre'] != ortho1['Grupo_pos']).astype(int)

In [16]:
# verificar o numero de linhas e de colunas após a limpeza dos dados
ortho1.shape

(262, 23)

In [25]:
# verificar os tipos de variaveis 
ortho1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 262 entries, 0 to 264
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Idade         262 non-null    int64
 1   Sexo          262 non-null    category
 2   Peso          262 non-null    int64
 3   Altura_cm     262 non-null    int64
 4   IMC           262 non-null    float64
 5   Grupo_pre     262 non-null    category
 6   Grupo_pos     262 non-null    category
 7   Fle_0         262 non-null    int64
 8   EVA_0         262 non-null    int64
 9   PM6_0         262 non-null    int64
 10  WD_0          262 non-null    int64
 11  WR_0          262 non-null    int64
 12  WAtotal_0     262 non-null    int64
 13  WT_0          262 non-null    int64
 14  Fle_90        262 non-null    int64
 15  EVA_90        262 non-null    int64
 16  PM6_90        262 non-null    int64
 17  WD_90         262 non-null    int64
 18  WR_90         262 non-null    int64
 19  WAtotal_90    262 non-null    int64
 20  WT_90         262 non-null    int64
 21  Satisfação    262 non-null    int64
 22  mudanca_CPAK  262 non-null    int64
dtypes: category(3), float64(1), int64(19)
memory usage: 44.6 KB

In [24]:
# uniformizar os tipos de variaveis para corresponder ao tipo real da variavel, 
# por exemplo, a variavel "Grupo_pre" e "Grupo_pos" são do tipo int, mas na verdade são categorias.
ortho1['Sexo'] = ortho1['Sexo'].astype('category')
ortho1['Grupo_pre'] = ortho1['Grupo_pre'].astype('category')
ortho1['Grupo_pos'] = ortho1['Grupo_pos'].astype('category')

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_20352\4159326153.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1['Sexo'] = ortho1['Sexo'].astype('category')
C:\Users\Eduardo\AppData\Local\Temp\ipykernel_20352\4159326153.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1['Grupo_pre'] = ortho1['Grupo_pre'].astype('category')
C:\Users\Eduardo\AppData\Local\Temp\ipykernel_20352\4159326153.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1['Grupo_pos'] = ortho1['Grupo_pos'].astype('category')

In [36]:
# avaliar consistencia dos dados, verificando se existem valores fora do esperado para cada variavel
ortho1.describe()

,Idade,Peso,Altura_cm,IMC,Fle_0,EVA_0,PM6_0,WD_0,WR_0,WAtotal_0,WT_0,Fle_90,EVA_90,PM6_90,WD_90,WR_90,WAtotal_90,WT_90,Satisfação,mudanca_CPAK
count,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000,262.000000
mean,71.133588,84.377863,169.038168,36.565258,116.858779,28.309160,263.759542,10.744275,3.068702,38.538168,48.538168,112.667939,16.767176,315.606870,2.729008,1.270992,10.740458,14.740458,46.633588,0.099237
std,7.658498,81.752397,73.659921,84.693225,97.667192,148.909188,130.702931,3.476173,2.745085,60.833203,16.005880,79.091249,122.551933,108.510827,2.455551,1.286177,7.969855,10.269613,190.084704,0.299552
min,47.000000,32.000000,136.000000,14.222222,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,70.000000,0.000000,121.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,66.000000,66.250000,155.000000,26.147508,95.000000,4.000000,180.000000,9.000000,2.000000,26.000000,37.250000,95.000000,0.000000,249.000000,1.000000,0.000000,5.000000,8.000000,8.000000,0.000000
50%,72.000000,76.000000,162.000000,28.725735,110.000000,6.000000,253.500000,10.000000,3.000000,34.000000,47.000000,105.000000,1.000000,300.000000,2.000000,1.000000,9.000000,13.000000,10.000000,0.000000
75%,76.000000,86.750000,170.000000,32.015277,120.000000,8.000000,330.000000,13.000000,4.000000,43.750000,59.000000,116.000000,3.000000,360.000000,4.000000,2.000000,15.000000,20.000000,10.000000,0.000000
max,89.000000,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,20.000000,31.000000,999.000000,96.000000,999.000000,999.000000,999.000000,11.000000,8.000000,40.000000,55.000000,999.000000,1.000000

In [37]:
# converter todos os 999 para NaN, pois são valores de preenchimento e 
# não representam dados reais
import numpy as np
ortho1.replace(999, np.nan, inplace=True)

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_20352\910569346.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ortho1.replace(999, np.nan, inplace=True)

In [38]:
#verificação de valores nulos em ortho1
ortho1.isnull().sum()

Idade            0
Sexo             0
Peso             2
Altura_cm        2
IMC              2
Grupo_pre        0
Grupo_pos        0
Fle_0            3
EVA_0            6
PM6_0            3
WD_0             0
WR_0             0
WAtotal_0        1
WT_0             0
Fle_90           2
EVA_90           4
PM6_90           2
WD_90            0
WR_90            0
WAtotal_90       0
WT_90            0
Satisfação      10
mudanca_CPAK     0
dtype: int64

In [46]:
#criação de um novo dataframe apenas com as variáveis pré-operatórias, 
# para análise exploratória
ortho_pre = list(ortho1[['Sexo', 'Grupo_pre', 'Fle_0', 'EVA_0', 'PM6_0', 'WD_0', 'WR_0', 'WAtotal_0', 'WT_0']])
ortho_pre

['Sexo',
 'Grupo_pre',
 'Fle_0',
 'EVA_0',
 'PM6_0',
 'WD_0',
 'WR_0',
 'WAtotal_0',
 'WT_0']

In [ ]:
ortho

In [ ]:
# vamos verificar a distribuição da nossa variavel target "mudanca_CPAK"
# para verificar se existe um desbalanceamento entre as classes, ou seja,
# se existem mais casos de mudança do que de não mudança ou vice-versa.
# Combinando absoluto e percentagem
dist_target = pd.DataFrame({
    'Contagem': ortho1['mudanca_CPAK'].value_counts(),
    'Percentagem': ortho1['mudanca_CPAK'].value_counts(normalize=True) * 100
})
print(dist_target)

              Contagem  Percentagem
mudanca_CPAK
0                  236    90.076336
1                   26     9.923664

In [28]:
# comparar a distribuição de mudanca_CPAK com Grupo_pre
# usando crosstab para ver a relação entre as variáveis

# Tabela de contingência (valores absolutos)
crosstab_abs = pd.crosstab(ortho1['Grupo_pre'], ortho1['mudanca_CPAK'], margins=True)
print("Distribuição Absoluta - mudanca_CPAK por Grupo_pre:")
print(crosstab_abs)

print("\n")

# Tabela de contingência (percentagem por linha - qual a percentagem de mudança em cada grupo pré)
crosstab_perc = pd.crosstab(ortho1['Grupo_pre'], ortho1['mudanca_CPAK'], normalize='index') * 100
print("Distribuição em Percentagem (por Grupo_pre):")
print(crosstab_perc.round(2))

Distribuição Absoluta - mudanca_CPAK por Grupo_pre:
mudanca_CPAK    0   1  All
Grupo_pre
1              13   0   13
2              24   3   27
3              16   0   16
4              29   0   29
5              94  15  109
6              51   6   57
7               4   1    5
8               2   1    3
9               3   0    3
All           236  26  262


Distribuição em Percentagem (por Grupo_pre):
mudanca_CPAK       0      1
Grupo_pre
1             100.00   0.00
2              88.89  11.11
3             100.00   0.00
4             100.00   0.00
5              86.24  13.76
6              89.47  10.53
7              80.00  20.00
8              66.67  33.33
9             100.00   0.00

In [30]:
# tabela combinada com valores absolutos e percentagens por Grupo_pre
contagem = pd.crosstab(ortho1['Grupo_pre'], ortho1['mudanca_CPAK']).reindex(columns=[0, 1], fill_value=0)
percentagem = (
    pd.crosstab(ortho1['Grupo_pre'], ortho1['mudanca_CPAK'], normalize='index')
    .reindex(columns=[0, 1], fill_value=0)
    .mul(100)
    .round(2)
)

tabela_comparacao = pd.DataFrame({
    'Sem_mudanca_n': contagem[0],
    'Com_mudanca_n': contagem[1],
    'Sem_mudanca_%': percentagem[0],
    'Com_mudanca_%': percentagem[1],
    'Total': contagem.sum(axis=1)
})

print(tabela_comparacao)

           Sem_mudanca_n  Com_mudanca_n  Sem_mudanca_%  Com_mudanca_%  Total
Grupo_pre
1                     13              0         100.00           0.00     13
2                     24              3          88.89          11.11     27
3                     16              0         100.00           0.00     16
4                     29              0         100.00           0.00     29
5                     94             15          86.24          13.76    109
6                     51              6          89.47          10.53     57
7                      4              1          80.00          20.00      5
8                      2              1          66.67          33.33      3
9                      3              0         100.00           0.00      3